title: Rishabh Agrawal
description: Senior Engineer, AI at AWS
url: https://rishabhagrawal1.github.io
exclude:
  - _posts
  - _layouts
  - _includes
  - public
  - atom.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
